- name: "Copy Compiled Back-End Files to EC2"
  become: true
  copy:
    src: /root/project/backend/dist/
    dest: /home/ubuntu/backend

- name: "Install node dependencies"
  become: true
  shell: |
    cd backend/
    npm i 

- name: "PM2 Start"
  become: true
  shell: |
    cd backend/
    pm2 start npm --name backend -- start